FROM python:3.7.1
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

#~ https://hub.docker.com/r/library/python/
#~ https://hub.docker.com/_/python/
#~ https://docs.docker.com/get-started/part2/#recap-and-cheat-sheet-optional
